const BodyText = () => {
    return (
      <p className="text-gray-700 leading-7">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Suspendisse potenti nullam ac tortor. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Massa enim nec dui nunc mattis enim ut tellus. Mi proin sed libero enim sed faucibus turpis in eu. Fames ac turpis egestas sed tempus urna et. Fames ac turpis egestas integer eget aliquet. At augue eget arcu dictum varius. Tellus rutrum tellus pellentesque eu. Sapien faucibus et molestie ac feugiat sed lectus. Quis auctor elit sed vulputate mi sit amet mauris. Erat nam at lectus urna duis convallis convallis tellus. Ultrices gravida dictum fusce ut placerat orci nulla pellentesque. Augue ut lectus arcu bibendum. Adipiscing elit ut aliquam purus sit amet.
  
  Sollicitudin nibh sit amet commodo. Ut etiam sit amet nisl purus in mollis nunc sed. Quis auctor elit sed vulputate mi sit amet mauris commodo. Diam maecenas ultricies mi eget mauris pharetra et ultrices neque. Arcu ac tortor dignissim convallis aenean. Non curabitur gravida arcu ac tortor dignissim convallis. A iaculis at erat pellentesque adipiscing commodo elit. Ipsum consequat nisl vel pretium lectus quam id. Praesent elementum facilisis leo vel fringilla est ullamcorper. Felis imperdiet proin fermentum leo vel orci porta non pulvinar. Amet luctus venenatis lectus magna fringilla urna porttitor. Dui faucibus in ornare quam viverra orci. Ut faucibus pulvinar elementum integer enim. Scelerisque fermentum dui faucibus in ornare quam. Lobortis mattis aliquam faucibus purus in massa.
  
  Ut tellus elementum sagittis vitae. Sapien eget mi proin sed libero enim sed faucibus. Quis commodo odio aenean sed adipiscing diam donec adipiscing. Dictum non consectetur a erat nam. Orci porta non pulvinar neque laoreet suspendisse. Elit ut aliquam purus sit amet luctus venenatis lectus magna. Odio aenean sed adipiscing diam. In nisl nisi scelerisque eu ultrices. Egestas egestas fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate. Tortor aliquam nulla facilisi cras. Sit amet nulla facilisi morbi tempus iaculis urna id. Varius vel pharetra vel turpis nunc eget. Vel pharetra vel turpis nunc. Velit sed ullamcorper morbi tincidunt ornare massa eget egestas purus. Odio facilisis mauris sit amet massa vitae tortor. Tincidunt id aliquet risus feugiat. Tempus iaculis urna id volutpat lacus laoreet non curabitur.
  
  Accumsan in nisl nisi scelerisque eu ultrices vitae. Eu turpis egestas pretium aenean pharetra magna ac placerat vestibulum. Nec feugiat nisl pretium fusce id velit ut. In egestas erat imperdiet sed euismod nisi. Non curabitur gravida arcu ac tortor dignissim convallis aenean et. Ultrices mi tempus imperdiet nulla. Sit amet aliquam id diam maecenas ultricies mi eget. Turpis egestas pretium aenean pharetra. Purus ut faucibus pulvinar elementum integer enim neque volutpat. Pulvinar neque laoreet suspendisse interdum consectetur libero id faucibus. Cursus in hac habitasse platea dictumst.
  
  Neque egestas congue quisque egestas diam in arcu cursus. Amet mauris commodo quis imperdiet massa tincidunt. Sed faucibus turpis in eu mi bibendum. Eu tincidunt tortor aliquam nulla facilisi cras fermentum odio eu. Mauris a diam maecenas sed enim ut sem. Facilisi nullam vehicula ipsum a. Adipiscing elit ut aliquam purus sit amet luctus venenatis. Non nisi est sit amet facilisis magna etiam. Cursus vitae congue mauris rhoncus. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Malesuada bibendum arcu vitae elementum curabitur vitae. Dolor morbi non arcu risus. Cursus eget nunc scelerisque viverra mauris in aliquam sem fringilla. Sed nisi lacus sed viverra tellus in hac habitasse. Eu volutpat odio facilisis mauris sit amet massa vitae tortor. In hac habitasse platea dictumst vestibulum. Senectus et netus et malesuada fames. Commodo nulla facilisi nullam vehicula ipsum a arcu. Gravida neque convallis a cras.
  
  Eget arcu dictum varius duis at. Tincidunt vitae semper quis lectus nulla at volutpat. Dictum at tempor commodo ullamcorper a. Sem integer vitae justo eget magna fermentum iaculis eu. Nullam eget felis eget nunc lobortis mattis aliquam faucibus purus. Turpis nunc eget lorem dolor sed viverra ipsum nunc. Consectetur adipiscing elit pellentesque habitant morbi. Placerat vestibulum lectus mauris ultrices eros in cursus. Sit amet risus nullam eget felis. Mi ipsum faucibus vitae aliquet nec ullamcorper sit amet risus. Id velit ut tortor pretium viverra suspendisse potenti nullam. Eros in cursus turpis massa tincidunt dui. Egestas sed tempus urna et pharetra pharetra massa. Quam pellentesque nec nam aliquam sem et. Scelerisque mauris pellentesque pulvinar pellentesque habitant morbi. Nibh cras pulvinar mattis nunc sed blandit libero volutpat sed. Orci ac auctor augue mauris augue neque. Cursus turpis massa tincidunt dui ut ornare. Semper quis lectus nulla at volutpat.
  
  Pharetra convallis posuere morbi leo urna. Morbi leo urna molestie at elementum. Commodo quis imperdiet massa tincidunt nunc pulvinar sapien et ligula. Amet nisl suscipit adipiscing bibendum est ultricies. Aliquam purus sit amet luctus venenatis lectus. Libero enim sed faucibus turpis. Enim nulla aliquet porttitor lacus. Nulla aliquet enim tortor at auctor. Augue ut lectus arcu bibendum. Porta non pulvinar neque laoreet. Blandit massa enim nec dui nunc mattis enim ut tellus. Id neque aliquam vestibulum morbi blandit cursus risus at.
  
  Amet purus gravida quis blandit turpis cursus. Malesuada nunc vel risus commodo. Nulla malesuada pellentesque elit eget. Massa sed elementum tempus egestas sed sed. Lectus arcu bibendum at varius vel pharetra vel turpis nunc. Non tellus orci ac auctor augue mauris augue. In fermentum posuere urna nec tincidunt. Laoreet suspendisse interdum consectetur libero. Elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus at. Aliquet lectus proin nibh nisl condimentum id venenatis a. Nec feugiat in fermentum posuere urna nec. Sed risus ultricies tristique nulla aliquet. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque. Commodo odio aenean sed adipiscing diam. Molestie a iaculis at erat pellentesque adipiscing commodo elit. Pharetra magna ac placerat vestibulum lectus mauris ultrices eros. Tellus molestie nunc non blandit massa enim nec. Nullam vehicula ipsum a arcu cursus vitae congue. Purus sit amet volutpat consequat mauris nunc congue.
  
  Vel fringilla est ullamcorper eget nulla facilisi etiam. Pretium fusce id velit ut tortor. Faucibus ornare suspendisse sed nisi lacus sed viverra. Vulputate dignissim suspendisse in est ante. Mi eget mauris pharetra et ultrices neque ornare. A erat nam at lectus urna duis convallis convallis tellus. Et tortor at risus viverra adipiscing. Nunc mattis enim ut tellus elementum. Nisi scelerisque eu ultrices vitae auctor eu. Massa ultricies mi quis hendrerit. Dolor purus non enim praesent elementum facilisis leo. Euismod in pellentesque massa placerat duis ultricies lacus sed. Nunc eget lorem dolor sed viverra ipsum nunc aliquet. Commodo odio aenean sed adipiscing diam donec adipiscing. Sed faucibus turpis in eu mi bibendum. Cras semper auctor neque vitae tempus quam pellentesque nec nam. Habitant morbi tristique senectus et netus et malesuada. Arcu felis bibendum ut tristique et egestas quis.
  
  Vel pharetra vel turpis nunc eget lorem dolor sed viverra. Eu sem integer vitae justo eget magna. In cursus turpis massa tincidunt. Tincidunt arcu non sodales neque sodales. Elementum nisi quis eleifend quam adipiscing vitae. Ut tortor pretium viverra suspendisse potenti nullam. Eu facilisis sed odio morbi quis commodo odio aenean sed. Aliquam purus sit amet luctus. Ut enim blandit volutpat maecenas. Diam vel quam elementum pulvinar etiam non. Ipsum a arcu cursus vitae congue. Nibh sit amet commodo nulla facilisi nullam vehicula. Ipsum nunc aliquet bibendum enim facilisis gravida neque.
  
  Neque vitae tempus quam pellentesque nec nam. Volutpat commodo sed egestas egestas. Risus ultricies tristique nulla aliquet. In hac habitasse platea dictumst vestibulum. Ipsum suspendisse ultrices gravida dictum fusce. Bibendum arcu vitae elementum curabitur vitae. In vitae turpis massa sed elementum tempus egestas sed sed. Sapien faucibus et molestie ac feugiat. Risus viverra adipiscing at in tellus integer. Nisl purus in mollis nunc sed id. Eget egestas purus viverra accumsan. Dignissim cras tincidunt lobortis feugiat vivamus at augue eget arcu. Elementum pulvinar etiam non quam lacus suspendisse. Risus in hendrerit gravida rutrum quisque non. Dui id ornare arcu odio. Fames ac turpis egestas maecenas pharetra convallis.
  
  Mauris vitae ultricies leo integer malesuada nunc vel. Sollicitudin ac orci phasellus egestas tellus rutrum. Nunc non blandit massa enim. Venenatis lectus magna fringilla urna porttitor rhoncus dolor purus. Praesent semper feugiat nibh sed pulvinar proin gravida. Id venenatis a condimentum vitae. Habitasse platea dictumst vestibulum rhoncus. Fermentum et sollicitudin ac orci phasellus egestas tellus. Vitae et leo duis ut diam. Eu volutpat odio facilisis mauris sit. Pellentesque diam volutpat commodo sed egestas.
  
  Vitae et leo duis ut diam quam nulla porttitor massa. Diam volutpat commodo sed egestas egestas. Potenti nullam ac tortor vitae. Et odio pellentesque diam volutpat commodo sed egestas egestas fringilla. Id diam vel quam elementum pulvinar. Scelerisque varius morbi enim nunc faucibus a pellentesque. Tortor at risus viverra adipiscing. Integer quis auctor elit sed vulputate mi sit amet mauris. Pulvinar etiam non quam lacus suspendisse faucibus interdum posuere. Sed pulvinar proin gravida hendrerit lectus. Eget mauris pharetra et ultrices neque ornare aenean euismod. Amet nisl suscipit adipiscing bibendum est ultricies integer quis auctor. Enim neque volutpat ac tincidunt. Nullam vehicula ipsum a arcu cursus vitae congue mauris. Pellentesque eu tincidunt tortor aliquam nulla facilisi cras fermentum. Libero volutpat sed cras ornare arcu dui vivamus. Sed risus ultricies tristique nulla aliquet. Eu lobortis elementum nibh tellus.
  
  Ornare aenean euismod elementum nisi quis eleifend. Dictum sit amet justo donec. Sagittis aliquam malesuada bibendum arcu vitae. Ipsum dolor sit amet consectetur adipiscing elit ut aliquam. Dictumst vestibulum rhoncus est pellentesque elit ullamcorper. Montes nascetur ridiculus mus mauris vitae ultricies leo integer malesuada. Tempus urna et pharetra pharetra. Sit amet est placerat in egestas erat. Lectus quam id leo in vitae turpis massa. Sed blandit libero volutpat sed cras ornare. Vel fringilla est ullamcorper eget nulla facilisi. Sed adipiscing diam donec adipiscing tristique risus nec. Gravida cum sociis natoque penatibus et. Sed augue lacus viverra vitae congue.
  
  Pulvinar pellentesque habitant morbi tristique senectus et. Ante in nibh mauris cursus mattis molestie a iaculis. Rhoncus urna neque viverra justo nec ultrices dui sapien. Nunc eget lorem dolor sed viverra ipsum nunc aliquet bibendum. Amet commodo nulla facilisi nullam. Ut aliquam purus sit amet luctus venenatis lectus magna. Ut faucibus pulvinar elementum integer. Pharetra magna ac placerat vestibulum lectus mauris ultrices eros in. Ut tellus elementum sagittis vitae et. Tincidunt praesent semper feugiat nibh. Pharetra vel turpis nunc eget lorem dolor sed viverra ipsum. Ut venenatis tellus in metus. Augue neque gravida in fermentum. Vitae tempus quam pellentesque nec. Ac turpis egestas integer eget aliquet nibh. Accumsan lacus vel facilisis volutpat est velit. Ultrices eros in cursus turpis massa tincidunt dui. Mauris vitae ultricies leo integer malesuada nunc. Eget nullam non nisi est sit. Amet consectetur adipiscing elit pellentesque habitant morbi.
  
  Sollicitudin nibh sit amet commodo nulla. Vitae sapien pellentesque habitant morbi. Vestibulum lorem sed risus ultricies tristique. Orci sagittis eu volutpat odio facilisis mauris sit amet. Pellentesque massa placerat duis ultricies lacus sed turpis tincidunt. Massa tincidunt nunc pulvinar sapien et. Ut consequat semper viverra nam libero. Sed enim ut sem viverra aliquet eget. Mi proin sed libero enim sed faucibus turpis in eu. Est ante in nibh mauris. A iaculis at erat pellentesque. Velit scelerisque in dictum non consectetur a erat nam. Rhoncus urna neque viverra justo nec ultrices. Diam in arcu cursus euismod quis viverra nibh cras. Vitae sapien pellentesque habitant morbi tristique senectus et netus. Metus aliquam eleifend mi in.
  
  Aliquam etiam erat velit scelerisque in dictum non. Egestas sed sed risus pretium quam vulputate. Neque viverra justo nec ultrices dui sapien eget mi proin. Senectus et netus et malesuada fames. Libero enim sed faucibus turpis in. Mi eget mauris pharetra et. Facilisis magna etiam tempor orci eu. Curabitur gravida arcu ac tortor dignissim convallis aenean et tortor. At erat pellentesque adipiscing commodo elit at imperdiet dui. Ornare aenean euismod elementum nisi quis eleifend quam. In mollis nunc sed id. Interdum velit euismod in pellentesque massa placerat duis ultricies lacus. Sapien pellentesque habitant morbi tristique senectus et netus et malesuada. Aliquet nibh praesent tristique magna sit amet.
  
  Tincidunt augue interdum velit euismod in pellentesque. Sagittis orci a scelerisque purus semper eget duis. Scelerisque varius morbi enim nunc faucibus a pellentesque. Feugiat vivamus at augue eget arcu dictum varius duis. Leo vel fringilla est ullamcorper eget nulla facilisi. Dolor sit amet consectetur adipiscing elit duis tristique sollicitudin. Pellentesque nec nam aliquam sem et tortor. Ut venenatis tellus in metus vulputate eu scelerisque. Sit amet porttitor eget dolor morbi non arcu risus. Odio euismod lacinia at quis risus sed. Turpis egestas integer eget aliquet nibh. Justo eget magna fermentum iaculis eu non. Cursus metus aliquam eleifend mi. Aliquet bibendum enim facilisis gravida neque convallis a cras. Elit duis tristique sollicitudin nibh sit.
  
  Nec dui nunc mattis enim ut tellus elementum sagittis. Eleifend mi in nulla posuere sollicitudin aliquam ultrices sagittis orci. Blandit aliquam etiam erat velit scelerisque in dictum non consectetur. Orci nulla pellentesque dignissim enim sit. In nisl nisi scelerisque eu ultrices vitae auctor. Gravida neque convallis a cras semper auctor neque vitae. Tristique sollicitudin nibh sit amet commodo nulla facilisi nullam vehicula. Sit amet aliquam id diam maecenas ultricies mi eget mauris. Netus et malesuada fames ac turpis egestas integer eget aliquet. Turpis in eu mi bibendum neque egestas congue quisque egestas. Ut aliquam purus sit amet luctus venenatis lectus magna. Dis parturient montes nascetur ridiculus mus mauris vitae ultricies.
  
  Tristique senectus et netus et malesuada fames. Vehicula ipsum a arcu cursus vitae congue mauris. Nulla at volutpat diam ut. Consectetur purus ut faucibus pulvinar elementum integer enim. Diam sollicitudin tempor id eu nisl nunc. Molestie ac feugiat sed lectus. Lacinia at quis risus sed vulputate odio ut enim blandit. Turpis massa tincidunt dui ut. Amet risus nullam eget felis eget nunc lobortis. Enim nulla aliquet porttitor lacus luctus. Nisi quis eleifend quam adipiscing vitae proin. Quam lacus suspendisse faucibus interdum posuere lorem. Sapien nec sagittis aliquam malesuada bibendum arcu vitae elementum curabitur. A scelerisque purus semper eget duis at tellus at urna. Egestas congue quisque egestas diam in arcu cursus euismod quis. Sit amet cursus sit amet.
      </p>
    )
  }
  
  export default BodyText